#### WORKFLOW #####
# Name of the Workflow
name: CICD

#### JOBS ####
jobs:
    code:
    needs: code
    ### STEPS ###
    runs-on: ubuntu-latest
     steps: # step
        name: Code checkout
        run: echo "Code checkout done"
        
    build:
    needs: code
    runs-on: ubuntu-latest ##runner-os
      steps:
        name: Code build with Docker
        run: echo "Docker todo"
        
    test:
    needs: code
    runs-on: ubuntu-latest
      steps:
        name: Code checkout
        run: echo "Code checkout done"
        
    deploy:
    needs: code
    runs-on: ubuntu-latest
      steps:
        name: Code checkout
        run: echo "Code checkout done"
